### ISSUE TITLE
Each time a packet is sent, ClientDisconnected event occurs

### ISSUE THREAD

**Issue by zzampong** [jchristn/CavemanTcp#1]
Hi Joel
I updated to 1.3.0.1 version this time but
Every time call send method,
ClientDisconnedted event occurs.
It didn't occur in previous version(1.2.1.2)

os: windows 10 pro (64bit)
framework:  .net core 3.1

**Comment by jchristn** [comment]
Hi @zzampong thanks for your note.  I'm unable to reproduce this on my side (see screenshots below) using the Test.Client and Test.Server projects.  I'm also using Windows 10 pro with .NET Core 3.1 in the test below.

Could you share a portion of code that isolates and reproduces this issue?

Cheers,
Joel


Server sending multiple messages to client:
![image](https://user-images.githubusercontent.com/1421081/93613007-22eac800-f985-11ea-9c12-efef82aac8fa.png)

Client sending multiple messages to server:
![image](https://user-images.githubusercontent.com/1421081/93613075-385ff200-f985-11ea-8b21-acad4708cde2.png)

Both implement the ```ClientDisconnected``` event:
```

        static void InitializeClient()
        {
            _Client = new CavemanTcpClient("127.0.0.1", 8000, false, null, null);
            _Client.Logger = Logger;

            _Client.Events.ClientConnected += (s, e) =>
            {
                Console.WriteLine("Connected to server");
            };

            _Client.Events.ClientDisconnected += (s, e) =>
            {
                Console.WriteLine("Disconnected from server");
            };
        }
```
and
```
        static void InitializeServer()
        {
            _Server = new CavemanTcpServer("127.0.0.1", 8000, false, null, null);
            _Server.Logger = Logger;

            _Server.Events.ClientConnected += (s, e) =>
            {
                Console.WriteLine("Client " + e.IpPort + " connected to server");
                _LastClient = e.IpPort;
            };

            _Server.Events.ClientDisconnected += (s, e) =>
            {
                Console.WriteLine("Client " + e.IpPort + " disconnected from server");
            };
        }
```

**Comment by jchristn** [comment]
Could you share a portion of code that isolates and reproduces this issue?

**Comment by zzampong** [comment]
I share the part of code.
As I checked again but ClientDisconnected event does not exactly occur in send method.
I found it occur after the read method.
And the event handler occurred, but the socket session seems to be still connected.
Because it could continue to read the data

              WriteResult wr = client.Send(sbuf);
                if (wr.Status == WriteResultStatus.Success)
                {
                    Console.WriteLine("Send Success");
                    
                    ReadResult rr = client.ReadWithTimeout(5000, 4);  // read header
                    if (rr.Status == ReadResultStatus.Success)
                    {
                        Console.WriteLine("Recived Success bytes: " + Encoding.UTF8.GetString(rr.Data));
                        
                        Array.Copy(rr.Data, 1, RecvBuf, 0, 3);
                        rr = client.ReadWithTimeout(5000, rr.Data[3]);  // read body
                        if (rr.Status == ReadResultStatus.Success)
                        {
                            //Console.WriteLine("Retrieved bytes: " + Encoding.UTF8.GetString(rr.Data));
                            Array.Copy(rr.Data, 0, RecvBuf, 3, RecvBuf[2]+1);

**Comment by jchristn** [comment]
Thanks @zzampong - could you enable logging and send me the console output?

i.e.

```
client.Logger = Logger;

private void Logger(string msg)
{
  Console.WriteLine(msg);
}
```

**Comment by zzampong** [comment]
Starting connection monitor for: 192.168.0.154:5400
Connected to server
Send Success                       ------> my log
Disconnected from server
Recived Success bytes: ��  ------> my log
Disconnected from server
[CavemanTcp.Client 192.168.0.154:5400] Client no longer connected to server
Disconnected from server

**Comment by jchristn** [comment]
Got it, thank you @zzampong - I was able to reproduce this issue.  My code to reproduce is here: https://github.com/jchristn/CavemanTcpTest

Will dig into this ASAP!

**Comment by jchristn** [comment]
Hi @zzampong thanks for finding this!  I've posted an update to NuGet (v1.3.0.4, see here: https://www.nuget.org/packages/CavemanTcp/1.3.0.4) and the commit is here: https://github.com/jchristn/CavemanTcp/commit/ed9674a8d6849f61b19f94341ae13cb41fe3e6b6

Please let me know if the issue continues!  Cheers, Joel
