### ISSUE TITLE
TcpServer - IsClientConnected problem

### ISSUE THREAD

**Issue by CetinOzdil** [jchristn/CavemanTcp#16]
Hello,

When using TcpServer my client connections were keep closing, after I dig a bit found out that [IsClientConnected](https://github.com/jchristn/CavemanTcp/blob/a4c0efa37d8ff6a48b5b44dd6eda900d72eff153/src/CavemanTcp/CavemanTcpServer.cs#L1169)  method returns false even when client is still connected. I don't know why but at
``` csharp
if (!client.Connected) return false;
```
```client.Connected``` returns false but client is still connected. Even I can send an receive data.

After searching a bit found out that ```client.Connected``` is not that reliable. At StackOverflow found out [this](https://stackoverflow.com/a/44242399) code and looks like it's working ok. 

``` csharp
public static TcpState GetState(this TcpClient tcpClient)
{
    var foo = IPGlobalProperties.GetIPGlobalProperties()
                                .GetActiveTcpConnections()
                                .FirstOrDefault(x => x.LocalEndPoint.Equals(tcpClient.Client.LocalEndPoint)
                                                     && x.RemoteEndPoint.Equals(tcpClient.Client.RemoteEndPoint));

    return foo != null ? foo.State : TcpState.Unknown;
}
```

**Comment by jchristn** [comment]
Thanks for bringing this to my attention!  Could you check v2.0.1 and let me know if this resolves the issue?

NuGet: https://www.nuget.org/packages/CavemanTcp/2.0.1
Commit: https://github.com/jchristn/CavemanTcp/commit/d0bc6c4fbd12d782d2e63795fc6d1a0c9d92e53f

**Comment by CetinOzdil** [comment]
Hello @jchristn , sorry for late reply, this update solved the problem for me. Thank you!
