### ISSUE TITLE
Undisposed CancellationTokenSource causing memory leak in Tcp Client timeout methods

### ISSUE THREAD

**Issue by akselatom** [jchristn/CavemanTcp#18]
**Operating system and version**: Windows 10 x64  
**Framework**: .NET 6.0  
**Issue encountered**: Memory leak due to non-disposal of `CancellationTokenSource` objects.  
**Expected behavior**: `CancellationTokenSource` objects should be properly disposed.

### Description:

Hi, I've encountered a memory leak issue similar to one that was previously resolved on the server side in [Issue #6](https://github.com/jchristn/CavemanTcp/issues/6). The client side seems to have a similar problem where linked `CancellationTokenSource` objects are not being disposed in the `SendWithTimeoutInternal` and `ReadWithTimeoutInternal` methods.

In async methods, the issue is only present in `ReadWithTimeoutInternalAsync`. `SendWithTimeoutInternalAsync` does not use `CreateLinkedTokenSource` (is that intentional?) and does not exhibit any visible issues, at least in dotMemory.

I’ve attached screenshots from dotMemory that highlight the memory leak. In my test, I used the `Test.Client` and `Test.ServerAsync` projects, repeatedly resending the same message to trigger the leak.

**Screenshots of the memory leak**:

![image](https://github.com/user-attachments/assets/9813b382-e28a-4ffc-bede-80d1c76df87e)  
![image](https://github.com/user-attachments/assets/f2095bfc-9365-4555-9520-d40bbc3ac11e)

### Suggested Solution:

- Wrap the `CancellationTokenSource` in a `using` statement.
- Or dispose of the `CancellationTokenSource` in a `finally` block within the mentioned methods.

**Comment by jchristn** [comment]
Thanks @akselatom for the detailed write up and for your patience.  I made the suggested changes and published to NuGet as v2.0.3.  Please let me know if you see any further issues and thanks for making the library better.
