### ISSUE TITLE
Random disconnect mid data transfer from client or server

### ISSUE THREAD

**Issue by LeaT113** [jchristn/CavemanTcp#5]
I'm really out of my wits with this. I'm creating an app to send data between computers, I've already raised an issue here a while back.
In essence, the connection is **randomly terminated**. Mid `Send` and `Read` on client and server respectively. I have made sure I am not calling any disconnect method on either. The `WriteResult` just returns as `Disconnected` at a random point during the process. I have considered **Keepalives** to be the cause and once disabled, it worked once, but I then reenabled and when I disabled again, it no longer worked. I am now at the state, where I send the same data over and over and there is seemingly a random % chance of the client or server disconnecting during the data transfer (unsure as to which one causes it). So I do not believe the Keepalives to be the cause of the problem, but they now are disabled on both.

The problem is on [this branch](https://github.com/LeaT113/TTransfer/tree/disconnect) of my app. The problem is centralized to the [TransferClient](https://github.com/LeaT113/TTransfer/blob/disconnect/TTransfer/Network/TransferClient.cs) and its `SendFile` function, which does the actual file data transfer. There, there is `result = client.Send(buffer);` and this result sometimes equals `WriteResultStatus.Disconnected`, because the `client` disconnects.
For reference, this is [my server class ](https://github.com/LeaT113/TTransfer/blob/disconnect/TTransfer/Network/TransferServer.cs).

Once again, I'm not calling for any disconnects myself. I have even completely disabled my disconnecting method `TerminateConnection` and it still happens.

Would appreciate any help, as this is a bit urgent and I really can't find anything else to try. I was sure it must be a bug in my code, but I have tried everything I could think off and it really doesn't seem like it, so maybe the Keepalives are enabled even with `Keepalive.EnableTcpKeepAlives = false`?

I should add that Keepalives shouldn't even have time to fail, as they were set to the default 5,5,5 for the values before I disabled them, and the error happens within the first 1-2 seconds of the connection, usually less. But I have also tested the Keepalives to detect a ethernet cable disconnect practically immediately, so I'm not sure how they work exactly.
Also from my test it seems that the client disconnects from the server, not the other way around, as the client's `Events_ClientDisconnected` seems to be called earlier then the server's.

**Comment by jchristn** [comment]
Can you get a Wireshark capture of this happening?

**Comment by LeaT113** [comment]
Never used Wireshark, but I'll try right away.

**Comment by LeaT113** [comment]
Okay, [here it is](https://drive.google.com/file/d/1Wpc5DwPdoLdVAT-I-X4AdVdm05ycKc-3/view?usp=sharing). `192.168.1.11` is the client and `192.168.1.16` is the server (aka receiver). This file contains the communication from the start of the connection to the "crash".

**Comment by jchristn** [comment]
Thanks.  Looks like the client is terminating (i.e. the presence of the FIN flag).

![image](https://user-images.githubusercontent.com/1421081/114475720-62496200-9bbe-11eb-8134-5f5c0275b04c.png)

I looked at your code and you have keepalives disabled (which is a good thing, if they were enabled it could be harder to troubleshoot).

When I looked through the rest of the trace, I see a lot of TCP window full messages.

How many bytes are you sending at a time and how many are you reading at a time?

Keep in mind the library has no control over what the OS itself does underneath it.  It could be a situation where the buffers are too full (not being drained fast enough) and the sender thinking the connection is failed.  

Also, does the transmission complete in its entirety and then it fails, or, does it fail mid transmission?  (or mid receipt)?

**Comment by LeaT113** [comment]
Thank you for the response.

I do believe it does have something to do with the data size.

I segment the file and send each part individually. That's the `SettingsData.MaxBufferSize` variable, it's in bytes. Both client and server (send and read) use this, so it's the same for both.
It had been set to `1024` bytes for the majority of the development. I believe I had not run into may random disconnects during dev, so I hadn't noticed. 
I was experimenting with it yesterday while trying to fix this issue and set it to `1048576` or a MiB. It made the errors more consistent (happening more often), but also increased the speed of the data transfer.

I just tried settings it to 512, which slows down the transfer speed dramatically (from 80+MB/s to 15-30MB/s. The issue seems to be almost completely gone. I test it by repeatedly sending a folder of data. When I wait about a second after a transfer has completed before I start a new one, it doesn't seem to show any issues.
But if I do it fast and start another transfer almost as soon as the previous one completes, it still crashes, though much less often then on 1048576.

If the solution would be to dramatically limit the speed of the connection, it wouldn't make sense to me. I have tested [D-lan](https://www.d-lan.net/), which is a similar app for sending data between computers and it was able to achieve almost theoretical max speeds of the gigabit connection (110MB/s or about 900Mb/s) on the same network with the same 2 computers.


I did wonder how the buffers in TCP work, or what happens when sender sends data much faster, then the receiver can read, but I don't see a reason for why it would be happening here.

It does seem to be tied to the network congestion. But the server never lags behind from the look at my progress bar, they always finish at the same time, so I do not believe the receiver (server) couldn't read fast enough.

**Comment by jchristn** [comment]
If the sender is unable to send due to unacknowledged segments, it is likely to think that there is either a) congestion or b) packet loss.  The sender literally thinks it cannot send any more data, and disconnects.  This can definitely reset a connection, and is unfortunately handled underneath my library.

You may want to consider using something with framing.  Then you get out of the business of managing read state.

**Comment by LeaT113** [comment]
Alright, and can I somehow detect how much more I can send before it's considered full and slow down the upload? Because that's the only way I can think of to avoid this and it's strange that it even is a problem, as the D-lan app I tested uploaded even faster and was fine. And I'm pretty sure my receiver can read fast enough. 
If you could point me to a resource about how the buffers on each end work, I'd be very grateful.

And I am afraid external framing would slow down the upload process. I am doing my own framing for the data transfer, so the receiver knows exactly how much it needs to read.

**Comment by jchristn** [comment]
The underlying APIs don't expose (AFAIK) the state of the buffers (maybe the do, but I haven't seen them).  

Are you sure framing would be too slow?  Have you tried WatsonTcp?

Could you link to the D-lan app so I can examine how it works under the hood?

**Comment by LeaT113** [comment]
I'm of course not sure, I would have to implement this whole thing again with WatsonTcp in mind to see.
If I am unable to fix this, I might rework it someday, but I'd like to avoid that, if possible. 

But from quickly looking at WatsonTcp, it would have some beneficial features, but it seems that every transmission is framed. What I do is I send a frame with info about how large a file is, it's name, etc. Then I send parts of the file with no frame, because all the receiver needs to do is append the bytes it receives onto the file, until it has read the specified filesize (byte count). Framing each of those subsequent messages would be unnecessary I feel like and may slow the connection down. And the streams in WatsonTcp are sent in one piece I see. If I used a stream, I would avoid the extra framing probably, but I would have to encrypt the whole file in memory, instead of piece by piece, which would be a big limitation. Right now, I encrypt and decrypt each part of the file right before sending / receiving, which allows for no additional memory to be required when sending large files.

Here's [D-link](https://www.d-lan.net/).

I've had a friend take a look at the Wireshark file and they said the congestion happens on the receiver, not sender. So I tried removing the file writing (which I use `FileStream.Write` for) and now it runs without fault at near the theoretical max speed.
So it seems to be the receiver being too slow. I don't think my disks are too slow, the usual modern hard drive reaches 150MB/s and the network goes at max 100MB/s. I'm looking at faster ways to write to a file, but I'm not sure I'll have any look.

**Comment by jchristn** [comment]
What size reads are you doing from the network, and what is the size of the buffer you're writing to the filestream?

**Comment by LeaT113** [comment]
So, I have made big progress. 

I had no idea about FileStream buffers. The default is 4KiB I have found. I have increased that to 512KiB and also reworked the FileStream a bit and it seems to be basically fixed. I have run into the issue twice in a few tens of tries. It seems to be consistently ok, as long as I don't transfer right after one is finished. One error was right after restart though.

I am reading 16KiB per loop and sending half of that (it was an experiment to see if it would help, by itself made no change, probably irrelevant). And the speeds are usually around 100MB/s. And the filestream buffer is now 512 KiB as I said.

So it seems to be almost completely ok.
The code is now on the branch, main changes are in [TransferServer's ReceiveFile](https://github.com/LeaT113/TTransfer/blob/disconnect/TTransfer/Network/TransferServer.cs).

**Comment by jchristn** [comment]
Hi @LeaT113 for your remote connection scenario, what do you see in the Wireshark capture?

**Comment by LeaT113** [comment]
Hi @jchristn, sorry for the delay, I was very busy.
I have captured a more remote connection scenario and it seems once again, the client (sender) 1.11 sends a FIN packet to the server 1.10
[Here's the capture.](https://drive.google.com/file/d/1XJxtWh934Zc7u-y68EsMlR-uephkE6uj/view?usp=sharing)

I was told earlier by a networking friend, that the TCP buffers should automatically resize and adapt to the network and that that would most likely avoid the issue, so they were surprised I even have this problem in the first place.

**Comment by jchristn** [comment]
Hi @LeaT113 - Windows will resize, but buffers do not. I think you're running into a situation where the window is exhausted due to unacknowledged segments. 

Thanks for sending the capture, I will take a look ASAP

**Comment by jchristn** [comment]
Doesn't look like window exhaustion.  It's remaining constant near 64KB.  It seems like the underlying stream is getting read out in anywhere from 1KB to 16KB chunks (which should be fine).

Out of curiosity, what happens if you try it without SSL?

**Comment by LeaT113** [comment]
Thanks for the timely response. I was calling it a buffer, but I'm not exactly sure on the right terminology, seems that I meant the window, thanks for the clarification.

I was under the impression I wasn't using SSL. I had a look into your code and it seems the default is `false` and I am using the constructor, which only takes in an **IP and a port**, so it doesn't change SSL to `true`. Thus I believe I'm not using SSL currently. But a `.._TemporaryKey.pfx` did appear in my project recently (I believe because I did a Release build for the first time) and I didn't know why, so I'm not sure.

**Comment by jchristn** [comment]
You mentioned you're doing your own framing?  That might be what is confusing Wireshark into thinking SSL is in there:
![image](https://user-images.githubusercontent.com/1421081/115163303-441bb000-a05d-11eb-812f-26c77593c19b.png)

If I were to decode this:
- 192.168.1.11 is your client
- 192.168.1.10 is your server
- the client is typically sending larger messages to the server (several KiB)
- the server typically doesn't send a response during transfer (other than the TCP-level ACK)

I do see some window full events:
![image](https://user-images.githubusercontent.com/1421081/115163385-b2607280-a05d-11eb-871b-5a96233c8620.png)

![image](https://user-images.githubusercontent.com/1421081/115163389-bab8ad80-a05d-11eb-9935-36e828416316.png)

![image](https://user-images.githubusercontent.com/1421081/115163397-c6a46f80-a05d-11eb-814f-1c1f23165800.png)

These seem fairly normal, and just indicative of a disparity in client write vs server read speeds (perhaps server is writing what it gets from the network to disk)

The FIN indicated in packet 2542 (client -> server) indicates that *something* is instructing the library to tear down (dispose) or otherwise call disconnect.  

Can you set the ```.Logger``` property in your client and server to ```Console.WriteLine``` or write it out to a file, and paste that output here?  Specifically, I'd like to see if this is invoked:
![image](https://user-images.githubusercontent.com/1421081/115163535-7c6fbe00-a05e-11eb-96b7-e3723e363d0a.png)


One thing I would look at right away is where the client and server are instantiated.  If they are in a forms/xaml app, form transitions have a weird way of disposing of objects (when you think they aren't going to).

**Comment by LeaT113** [comment]
Thank you for your continued help.

My TCP communication is divided into 2 modes. First, in `EstablishConnection` I'm using fixed length messages, as both the client and server know exactly what to expect, because they're following a sort of state machine.

For the file transfer, the client (sender) first sends a _13 byte_ message containing the _number of total items_ and their _total size_, so that the server knows how many times it should attempt to receive an item and what the total size is for a progress bar.
Then, for each item, the client first sends a _1033 byte_ "frame" which contains the _number of bytes for the file_ (irrelevant for folders) stored in _8 bytes_ and _1024 bytes for the relative filepath_. A large part of that will often be nulls, but the UTF8 decoding deals with it just fine. Thanks to that, I can keep a fixed width info message.
After that, it streams the contents of the file. The server reads data into a file until it has read the number of bytes specified by the client in this info message. So that's the "framing". 

Your decoding is correct.

And yes, the server is writing all the bytes received during a file transfer (apart from the initial info, which is the framing) to disk. But the client is reading it from disk, so I would expect that speed to be similar. The disk should be operating at around 150MB/s like regular HDDs. Same as the disk the client is reading from. 
I first guessed the problem would be the disk is not fast enough, but even at top speeds via the gigabit switch close connection, the transfer speeds reach only 100MB/s, so it shouldn't saturate the disk write fully. 
~~And the problem doesn't occur on the close connection, where I'm also writing to a regular HDD.~~ It does occur on the close connection, but when I was testing last time, it almost always worked. Now, with the same setup and contents, it fails much more often.



I have a custom Console in the application, which I use for text output. I set your client and server to output there (in purple, the rest are other custom notifications).  One log is from the sending device, the other from receiving. There are also timestamps for better orientation.

![TT_LOG](https://user-images.githubusercontent.com/48381592/115366758-de970300-a1c5-11eb-946a-7615ba51482e.png)
This was captured attempting a send on the gigabit close connection. So that also sometimes fails, today more then last time. It's really unpredictable and random.
One thing to note is I start a server on both devices on app startup, because the apps are equal. One can send to the other and vise versa. When one wants to send, it starts a client and connects to the other device's server, that is always running.


About the instantiation.. This is a WPF app. I have a `UserControl` for the network tab, which holds the instances of the `CavemanTcpServer` and `CavemanTcpClient` (when sending, then it's disposed of). This custom control never gets closed, it's part of the MainWindow, so it's always visible. I never navigate to a different window. The server is only disposed of on app exit.

**Comment by jchristn** [comment]
The statement ```[CavemanTcp.Client 192.168.1.16:11501] disconnected``` tells me that the ```ConnectionMonitor``` is detecting a disconnect, or, there is a ```SocketException```, ```TaskCanceledException```, or ```OperationCanceledException```.

I'll modify it today to add more logging verbosity, along with a configuration flag to disable it.  Hopefully the verbosity will give us more clarity on what may be causing it.  Thanks for doing this, I'll get on it.

**Comment by jchristn** [comment]
Hi @LeaT113 I just pushed NuGet v1.3.5 (https://www.nuget.org/packages/CavemanTcp/1.3.5), commit is here (https://github.com/jchristn/CavemanTcp/commit/2323b414091676f0178efb51fcfd6eacbd4a9717)

This release does two things:
1) additional debug logging on ```ConnectionMonitor``` (including exceptions) and ```IsClientConnected```
2) ability to disable ```ConnectionMonitor``` via ```CavemanTcpClientSettings.EnableConnectionMonitor = false```

Could you try the new version with the ```ConnectionMonitor``` enabled, and post the log results?

Thanks, Joel

**Comment by LeaT113** [comment]
Hi, great idea, thanks for the fast commit.
Coincidentally, I should also improve my exception tracking and printing, as with generic errors, it's often hard to say what exactly the problem was in my app.

Installed the commit, did the exact same test. Here are the logs, once again in purple.
Seems the important part is `unable to poll client socket` on the client.

![TT_LOG1](https://user-images.githubusercontent.com/48381592/115439916-63f2d580-a20f-11eb-9629-b216f7b74653.png)

**Comment by jchristn** [comment]
Thank you.  I have two potential solutions, both of them will require another update.

1) Add a ```lock``` around the socket polling in ```IsClientConnected```.  I can't find anything definitive that indicates whether or not the ```Socket.Poll``` API is thread-safe. 

2) Modify the poll ```microseconds``` parameter to be greater than zero.  It may be that it's simply not waiting long enough for a response due to the system being busy.

Could you give v1.3.6 a try?  NuGet: https://www.nuget.org/packages/CavemanTcp/1.3.6  Commit: https://github.com/jchristn/CavemanTcp/commit/d3f22005171e8c71c2d0cbc8ed47059ce78f73d4

**Comment by LeaT113** [comment]
Thank you for the very fast patch.

I have tested the new version. It seems to be stable. I am still testing the close gigabit connection.
I kept the advanced logging on. The transfer does not seem to have failed even once.
I have tested 16 times fast in a row (which previously often caused issues) and it has finished the operation every time.

It usually logged the regular things, but it has given me this twice.

![TTransfer_WIVnAilOX3](https://user-images.githubusercontent.com/48381592/115444920-7d971b80-a215-11eb-8785-0b71c99a66f9.png)

Keep in mind it still successfully transferred all data in those cases.

**Comment by LeaT113** [comment]
Correction, it has failed now. Right on the 17th try. I left the app running minimized while writing this, then tried it again and it failed. Then I tried a few more times and no issue.

The error seems to be the same as before. Again from the client:
![image](https://user-images.githubusercontent.com/48381592/115445435-204f9a00-a216-11eb-81fc-fde5275cc697.png)

**Comment by jchristn** [comment]
For the ```SocketException```, I can address that by adding a ```_Disposing``` bool to the code.  

For the second one, can you see if it happens consistently when you minimize/maximize?

**Comment by jchristn** [comment]
Try this one please (v1.3.7) - NuGet https://www.nuget.org/packages/CavemanTcp/1.3.7  commit https://github.com/jchristn/CavemanTcp/commit/a57d35468044e2a535778347e615c7db99dcd545

This one sets the polling interval to ```-1``` by default.

Also please let me know about behavior while minimizing/maximizing.

**Comment by LeaT113** [comment]
I have not found a correlation with minimizing.
I tested by sending 20 times in a row with a pause between transfers, no issues. I think the SocketException log popped up once or twice.

I later tried to send very fast, the `unable to poll client socket` happened after 7 successful tries and then again after 17. The SocketException was logged almost every try.
So at least for this gigabit connection, it seems to be almost fine. I don't have access to the remote computer now, but I will be able to test that tomorrow. For now, this close connection seems to be a decent measure.

I'm downloading the new version now, will let you know.

**Comment by LeaT113** [comment]
This is flawless. 
I ran about 20 transfers back to back, no pause, neither error popped up.

**Comment by jchristn** [comment]
Man, that is good to hear.  

Let's leave it open for now in case the issue rears its head again.

Seems like the socket polling I was doing was a little too aggressive in terms of its expectation of a response from the kernel.  Setting it to ```-1``` may have given it the buffer it needed to actually get a response back indicating that everything was ok.

**Comment by LeaT113** [comment]
Interrupting the connection works wonders too!

It now doesn't crash, doesn't disconnect, nothing. Both sides just pause. I then reconnected the ethernet cable and they simply continue and finish the transfer, 0 issues. This is perfect! So now I have the option of just waiting for the connection to resume, potentially saving gigabytes of a half-sent file from having to be resent again.

And, if I enable Keepalives, everything works just fine and when I interrupt the connection, it immediately disconnects, just like it's supposed to. I'll put that up to the user, in the settings with some additional checks. 

This is sublime! **Thank you** so much @jchristn! 
I never expected this to actually be solved, it just seemed like a thing that happens. You persisted and managed to solve it after so much back and forth.. I appreciate it. 
I will test the remote connection tomorrow, but I fully believe it will be without fault. Maybe then this issue can be closed.
I am just a student, but I will be sending a few dollars your way on PayPal, you have really helped me, especially since this is my final project in high school. Thank you.

**Comment by jchristn** [comment]
My pleasure @LeaT113 - thank you for making the library better!  I appreciate the support!  Hope your project goes super smooth!

**Comment by jchristn** [comment]
Hi @LeaT113 how did it go with the remote connection?

**Comment by LeaT113** [comment]
Hi, sorry, have gotten busy with work. Yes, it works exactly as it should, tested on 7GB UE build, no issues. I believe it to be fixed in this form.
I will put my app to more tests later, once I finish this version and create a Release. Perhaps you can then try, what you've even been helping with this whole time. 

But yeah, this works perfectly.

**Comment by jchristn** [comment]
Awesome @LeaT113 - happy to give it a go!  I'll close this out for now - please feel free to file another issue, start a discussion, email, whatever when you'd like me to put your app through its paces.  Again thanks for making the library *much* better.
