### ISSUE TITLE
Memory leak that caused by detached CancellationTokenSource objects

### ISSUE THREAD

**Issue by SaintedPsycho** [jchristn/CavemanTcp#6]
Operating system and version: Windows 10 x64, .NET Framework 4.7.2.
Issue encountered: Memory leak.
Expected behavior: CancellationTokenSource objects are disposed.

Hi. I've been using HttpServerLite and found a memory leak inside related CavemanTcp library during my investigation. There is also a place without proper resources disposal in HttpServerLite, but it's pretty minor (`_TokenSource` is canceled but not disposed in `Dispose` method of **Webserver.cs**). That memory leak is caused by creating CancellationTokenSource and leaving them hanging in memory. Therefore the more requests incoming, the more detached CancellationTokenSource objects are piling in the second Heap generation.

This leaking CancellationTokenSource issue relevant for the next methods inside **CavemanTcpServer.cs**:
- AcceptConnections() [my main concern]
- SendWithTimeoutInternal(...)
- SendWithTimeoutInternalAsync(...)
- ReadWithTimeoutInternal(...)
- ReadWithTimeoutInternalAsync(...)

Also, in synchronous Start() method there is double _TokenSource assignment that lead us to one detached CancellationTokenSource.

As possible solution for CancellationTokenSource disposal in AcceptConnections(), i can suggest the next code that helped me in my tests.
```
var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(_Token, client.Token);
var _ = HandleClientConnection(client, linkedCts.Token)
        .ContinueWith(x => linkedCts.Dispose())
        .ConfigureAwait(false);
```
In case of other unhandled places we can use for example `using` or `try{}finally{}`.
To prove CancellationTokenSource memory leak there is a screenshots from dotMemory profiler with fixes and without + list of alive objects where CancellationTokenSource at the top with extremely high number of retained bytes.

![Screenshot 2022-01-13 194350](https://user-images.githubusercontent.com/13201803/149382424-3f036e8a-cdcf-4fa8-ba5a-975b66052926.jpg)
![Screenshot 2022-01-13 194356](https://user-images.githubusercontent.com/13201803/149382418-e627c625-9ba5-4a70-a933-ee37a80c4f1d.jpg)
![Screenshot 2022-01-13 194817](https://user-images.githubusercontent.com/13201803/149382423-8b4d929d-ac4e-46f1-ae2c-3709a570db47.jpg)

**Comment by jchristn** [comment]
Hi @SaintedPsycho thanks for pointing this out, working on a fix now!

**Comment by jchristn** [comment]
Just pushed v1.3.8.3 (and added you to the README):

- NuGet: https://www.nuget.org/packages/CavemanTcp/1.3.8.3
- Commit: https://github.com/jchristn/CavemanTcp/commit/f31cb68215bddf289dc1c1b1174f15480b01956e

I will get the deps updated in HttpServerLite next.  Please let me know if this doesn't fix the issue or if there are any other changes!

I will report back once HttpServerLite is updated, too.

**Comment by jchristn** [comment]
HttpServerLite fix (also added you to the README there):

- NuGet: https://www.nuget.org/packages/HttpServerLite/1.2.1.6
- Commit: https://github.com/jchristn/HttpServerLite/commit/1b16152d354d0c73f4c7929ac9dc8ce002c78f6e

Please let me know if this makes life better!

**Comment by SaintedPsycho** [comment]
Hi @jchristn. Great. Everything seems alright. Thank you.
